# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MyNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyNotes
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
  target 'MyNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyNotesUITests' do
    # Pods for testing
  end

end
