# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notebook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Notebook
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'NotebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotebookUITests' do
    # Pods for testing
  end

end
